# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
# permalink:        pretty
# relative_permalinks: true

gems:
  - jekyll-paginate

# Setup
title:            Evgeny Garlukovich
description:      'Software Engineer'
url:              https://evgenygarl.github.io/
baseurl:          /

author:
  name:           'Evgeny Garlukovich'
  url:            'https://evgenygarl.github.io/'
  email:          'https://www.google.com/recaptcha/mailhide/d?k=01Jp-yxgTF5a2ZX4XAikqomA==&c=xx0oSgmfzzwE6lwA3aZX3oYVKsfiEEwVZ8vIE26obxU='
  github:         'https://github.com/evgenygarl'
  twitter:        'https://twitter.com/evgenygarl'
  linkedin:       'https://www.linkedin.com/in/evgenygarlukovich/'
  telegram:       'https://t.me/evgenygarlukovich'

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
