# Dependencies
markdown:         kramdown
highlighter:      rouge

plugins:
  - jekyll-paginate

# Permalinks
permalink:        /blog/:year/:month/:day/:title/

# Setup
title:            Evgeny Garlukovich
description:      'Software Engineer'
url:              https://evgenygarl.github.io/
baseurl:          ''

author:
  name:           'Evgeny Garlukovich'
  url:            'https://evgenygarl.github.io/'
  email:          'https://www.google.com/recaptcha/mailhide/d?k=01Jp-yxgTF5a2ZX4XAikqomA==&c=xx0oSgmfzzwE6lwA3aZX3oYVKsfiEEwVZ8vIE26obxU='
  github:         'https://github.com/evgenygarl'
  twitter:        'https://twitter.com/evgenygarl'
  linkedin:       'https://www.linkedin.com/in/evgenygarlukovich/'
  telegram:       'https://t.me/evgenygarlukovich'

paginate:         5

excerpt_separator: <!--more-->

google_analytics: 'UA-49313480-2'
